/**
 * Countries/regions where Claude (Anthropic) is available — used as the
 * registration-country label on onboarded accounts (a local tag folded into
 * notes; Sub2API has no country field). Source: anthropic.com/supported-countries.
 * Deliberately excludes unsupported places (e.g. mainland China, Hong Kong,
 * Macau, Russia). United States is first so it can be the default.
 */
export type ClaudeCountry = { code: string; zh: string; en: string };

export const DEFAULT_COUNTRY = "US";

export const CLAUDE_COUNTRIES: ClaudeCountry[] = [
  { code: "US", zh: "美国", en: "United States" },
  { code: "AL", zh: "阿尔巴尼亚", en: "Albania" },
  { code: "DZ", zh: "阿尔及利亚", en: "Algeria" },
  { code: "AD", zh: "安道尔", en: "Andorra" },
  { code: "AO", zh: "安哥拉", en: "Angola" },
  { code: "AG", zh: "安提瓜和巴布达", en: "Antigua and Barbuda" },
  { code: "AR", zh: "阿根廷", en: "Argentina" },
  { code: "AM", zh: "亚美尼亚", en: "Armenia" },
  { code: "AU", zh: "澳大利亚", en: "Australia" },
  { code: "AT", zh: "奥地利", en: "Austria" },
  { code: "AZ", zh: "阿塞拜疆", en: "Azerbaijan" },
  { code: "BS", zh: "巴哈马", en: "Bahamas" },
  { code: "BH", zh: "巴林", en: "Bahrain" },
  { code: "BD", zh: "孟加拉国", en: "Bangladesh" },
  { code: "BB", zh: "巴巴多斯", en: "Barbados" },
  { code: "BE", zh: "比利时", en: "Belgium" },
  { code: "BZ", zh: "伯利兹", en: "Belize" },
  { code: "BJ", zh: "贝宁", en: "Benin" },
  { code: "BT", zh: "不丹", en: "Bhutan" },
  { code: "BO", zh: "玻利维亚", en: "Bolivia" },
  { code: "BA", zh: "波斯尼亚和黑塞哥维那", en: "Bosnia and Herzegovina" },
  { code: "BW", zh: "博茨瓦纳", en: "Botswana" },
  { code: "BR", zh: "巴西", en: "Brazil" },
  { code: "BN", zh: "文莱", en: "Brunei" },
  { code: "BG", zh: "保加利亚", en: "Bulgaria" },
  { code: "BF", zh: "布基纳法索", en: "Burkina Faso" },
  { code: "BI", zh: "布隆迪", en: "Burundi" },
  { code: "CV", zh: "佛得角", en: "Cabo Verde" },
  { code: "KH", zh: "柬埔寨", en: "Cambodia" },
  { code: "CM", zh: "喀麦隆", en: "Cameroon" },
  { code: "CA", zh: "加拿大", en: "Canada" },
  { code: "CF", zh: "中非共和国", en: "Central African Republic" },
  { code: "TD", zh: "乍得", en: "Chad" },
  { code: "CL", zh: "智利", en: "Chile" },
  { code: "CO", zh: "哥伦比亚", en: "Colombia" },
  { code: "KM", zh: "科摩罗", en: "Comoros" },
  { code: "CG", zh: "刚果（布）", en: "Congo (Republic)" },
  { code: "CR", zh: "哥斯达黎加", en: "Costa Rica" },
  { code: "CI", zh: "科特迪瓦", en: "Côte d'Ivoire" },
  { code: "HR", zh: "克罗地亚", en: "Croatia" },
  { code: "CY", zh: "塞浦路斯", en: "Cyprus" },
  { code: "CZ", zh: "捷克", en: "Czechia" },
  { code: "DK", zh: "丹麦", en: "Denmark" },
  { code: "DJ", zh: "吉布提", en: "Djibouti" },
  { code: "DM", zh: "多米尼克", en: "Dominica" },
  { code: "DO", zh: "多米尼加", en: "Dominican Republic" },
  { code: "EC", zh: "厄瓜多尔", en: "Ecuador" },
  { code: "EG", zh: "埃及", en: "Egypt" },
  { code: "SV", zh: "萨尔瓦多", en: "El Salvador" },
  { code: "GQ", zh: "赤道几内亚", en: "Equatorial Guinea" },
  { code: "ER", zh: "厄立特里亚", en: "Eritrea" },
  { code: "EE", zh: "爱沙尼亚", en: "Estonia" },
  { code: "SZ", zh: "斯威士兰", en: "Eswatini" },
  { code: "ET", zh: "埃塞俄比亚", en: "Ethiopia" },
  { code: "FJ", zh: "斐济", en: "Fiji" },
  { code: "FI", zh: "芬兰", en: "Finland" },
  { code: "FR", zh: "法国", en: "France" },
  { code: "GA", zh: "加蓬", en: "Gabon" },
  { code: "GM", zh: "冈比亚", en: "Gambia" },
  { code: "GE", zh: "格鲁吉亚", en: "Georgia" },
  { code: "DE", zh: "德国", en: "Germany" },
  { code: "GH", zh: "加纳", en: "Ghana" },
  { code: "GR", zh: "希腊", en: "Greece" },
  { code: "GD", zh: "格林纳达", en: "Grenada" },
  { code: "GT", zh: "危地马拉", en: "Guatemala" },
  { code: "GN", zh: "几内亚", en: "Guinea" },
  { code: "GW", zh: "几内亚比绍", en: "Guinea-Bissau" },
  { code: "GY", zh: "圭亚那", en: "Guyana" },
  { code: "HT", zh: "海地", en: "Haiti" },
  { code: "HN", zh: "洪都拉斯", en: "Honduras" },
  { code: "HU", zh: "匈牙利", en: "Hungary" },
  { code: "IS", zh: "冰岛", en: "Iceland" },
  { code: "IN", zh: "印度", en: "India" },
  { code: "ID", zh: "印度尼西亚", en: "Indonesia" },
  { code: "IQ", zh: "伊拉克", en: "Iraq" },
  { code: "IE", zh: "爱尔兰", en: "Ireland" },
  { code: "IL", zh: "以色列", en: "Israel" },
  { code: "IT", zh: "意大利", en: "Italy" },
  { code: "JM", zh: "牙买加", en: "Jamaica" },
  { code: "JP", zh: "日本", en: "Japan" },
  { code: "JO", zh: "约旦", en: "Jordan" },
  { code: "KZ", zh: "哈萨克斯坦", en: "Kazakhstan" },
  { code: "KE", zh: "肯尼亚", en: "Kenya" },
  { code: "KI", zh: "基里巴斯", en: "Kiribati" },
  { code: "KW", zh: "科威特", en: "Kuwait" },
  { code: "KG", zh: "吉尔吉斯斯坦", en: "Kyrgyzstan" },
  { code: "LA", zh: "老挝", en: "Laos" },
  { code: "LV", zh: "拉脱维亚", en: "Latvia" },
  { code: "LB", zh: "黎巴嫩", en: "Lebanon" },
  { code: "LS", zh: "莱索托", en: "Lesotho" },
  { code: "LR", zh: "利比里亚", en: "Liberia" },
  { code: "LY", zh: "利比亚", en: "Libya" },
  { code: "LI", zh: "列支敦士登", en: "Liechtenstein" },
  { code: "LT", zh: "立陶宛", en: "Lithuania" },
  { code: "LU", zh: "卢森堡", en: "Luxembourg" },
  { code: "MG", zh: "马达加斯加", en: "Madagascar" },
  { code: "MW", zh: "马拉维", en: "Malawi" },
  { code: "MY", zh: "马来西亚", en: "Malaysia" },
  { code: "MV", zh: "马尔代夫", en: "Maldives" },
  { code: "ML", zh: "马里", en: "Mali" },
  { code: "MT", zh: "马耳他", en: "Malta" },
  { code: "MH", zh: "马绍尔群岛", en: "Marshall Islands" },
  { code: "MR", zh: "毛里塔尼亚", en: "Mauritania" },
  { code: "MU", zh: "毛里求斯", en: "Mauritius" },
  { code: "MX", zh: "墨西哥", en: "Mexico" },
  { code: "FM", zh: "密克罗尼西亚", en: "Micronesia" },
  { code: "MD", zh: "摩尔多瓦", en: "Moldova" },
  { code: "MC", zh: "摩纳哥", en: "Monaco" },
  { code: "MN", zh: "蒙古", en: "Mongolia" },
  { code: "ME", zh: "黑山", en: "Montenegro" },
  { code: "MA", zh: "摩洛哥", en: "Morocco" },
  { code: "MZ", zh: "莫桑比克", en: "Mozambique" },
  { code: "NA", zh: "纳米比亚", en: "Namibia" },
  { code: "NR", zh: "瑙鲁", en: "Nauru" },
  { code: "NP", zh: "尼泊尔", en: "Nepal" },
  { code: "NL", zh: "荷兰", en: "Netherlands" },
  { code: "NZ", zh: "新西兰", en: "New Zealand" },
  { code: "NI", zh: "尼加拉瓜", en: "Nicaragua" },
  { code: "NE", zh: "尼日尔", en: "Niger" },
  { code: "NG", zh: "尼日利亚", en: "Nigeria" },
  { code: "MK", zh: "北马其顿", en: "North Macedonia" },
  { code: "NO", zh: "挪威", en: "Norway" },
  { code: "OM", zh: "阿曼", en: "Oman" },
  { code: "PK", zh: "巴基斯坦", en: "Pakistan" },
  { code: "PW", zh: "帕劳", en: "Palau" },
  { code: "PS", zh: "巴勒斯坦", en: "Palestine" },
  { code: "PA", zh: "巴拿马", en: "Panama" },
  { code: "PG", zh: "巴布亚新几内亚", en: "Papua New Guinea" },
  { code: "PY", zh: "巴拉圭", en: "Paraguay" },
  { code: "PE", zh: "秘鲁", en: "Peru" },
  { code: "PH", zh: "菲律宾", en: "Philippines" },
  { code: "PL", zh: "波兰", en: "Poland" },
  { code: "PT", zh: "葡萄牙", en: "Portugal" },
  { code: "QA", zh: "卡塔尔", en: "Qatar" },
  { code: "RO", zh: "罗马尼亚", en: "Romania" },
  { code: "RW", zh: "卢旺达", en: "Rwanda" },
  { code: "KN", zh: "圣基茨和尼维斯", en: "Saint Kitts and Nevis" },
  { code: "LC", zh: "圣卢西亚", en: "Saint Lucia" },
  { code: "VC", zh: "圣文森特和格林纳丁斯", en: "Saint Vincent and the Grenadines" },
  { code: "WS", zh: "萨摩亚", en: "Samoa" },
  { code: "SM", zh: "圣马力诺", en: "San Marino" },
  { code: "ST", zh: "圣多美和普林西比", en: "São Tomé and Príncipe" },
  { code: "SA", zh: "沙特阿拉伯", en: "Saudi Arabia" },
  { code: "SN", zh: "塞内加尔", en: "Senegal" },
  { code: "RS", zh: "塞尔维亚", en: "Serbia" },
  { code: "SC", zh: "塞舌尔", en: "Seychelles" },
  { code: "SL", zh: "塞拉利昂", en: "Sierra Leone" },
  { code: "SG", zh: "新加坡", en: "Singapore" },
  { code: "SK", zh: "斯洛伐克", en: "Slovakia" },
  { code: "SI", zh: "斯洛文尼亚", en: "Slovenia" },
  { code: "SO", zh: "索马里", en: "Somalia" },
  { code: "SB", zh: "所罗门群岛", en: "Solomon Islands" },
  { code: "ZA", zh: "南非", en: "South Africa" },
  { code: "KR", zh: "韩国", en: "South Korea" },
  { code: "SS", zh: "南苏丹", en: "South Sudan" },
  { code: "ES", zh: "西班牙", en: "Spain" },
  { code: "LK", zh: "斯里兰卡", en: "Sri Lanka" },
  { code: "SD", zh: "苏丹", en: "Sudan" },
  { code: "SR", zh: "苏里南", en: "Suriname" },
  { code: "SE", zh: "瑞典", en: "Sweden" },
  { code: "CH", zh: "瑞士", en: "Switzerland" },
  { code: "TW", zh: "台湾", en: "Taiwan" },
  { code: "TJ", zh: "塔吉克斯坦", en: "Tajikistan" },
  { code: "TZ", zh: "坦桑尼亚", en: "Tanzania" },
  { code: "TH", zh: "泰国", en: "Thailand" },
  { code: "TL", zh: "东帝汶", en: "Timor-Leste" },
  { code: "TG", zh: "多哥", en: "Togo" },
  { code: "TO", zh: "汤加", en: "Tonga" },
  { code: "TT", zh: "特立尼达和多巴哥", en: "Trinidad and Tobago" },
  { code: "TN", zh: "突尼斯", en: "Tunisia" },
  { code: "TR", zh: "土耳其", en: "Türkiye" },
  { code: "TM", zh: "土库曼斯坦", en: "Turkmenistan" },
  { code: "TV", zh: "图瓦卢", en: "Tuvalu" },
  { code: "UG", zh: "乌干达", en: "Uganda" },
  { code: "UA", zh: "乌克兰", en: "Ukraine" },
  { code: "AE", zh: "阿联酋", en: "United Arab Emirates" },
  { code: "GB", zh: "英国", en: "United Kingdom" },
  { code: "UY", zh: "乌拉圭", en: "Uruguay" },
  { code: "UZ", zh: "乌兹别克斯坦", en: "Uzbekistan" },
  { code: "VU", zh: "瓦努阿图", en: "Vanuatu" },
  { code: "VA", zh: "梵蒂冈", en: "Vatican City" },
  { code: "VN", zh: "越南", en: "Vietnam" },
  { code: "ZM", zh: "赞比亚", en: "Zambia" },
  { code: "ZW", zh: "津巴布韦", en: "Zimbabwe" },
];
